name: dummy_yaml

environment:
  sdk: ">=2.18.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  bdd_widget_test:
    path: ../
  build_runner: ^2.1.7
  integration_test:
    sdk: flutter
  flutter_test:
    sdk: flutter
